# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(656, 592)
        MainWindow.setMinimumSize(QtCore.QSize(656, 592))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(548, 548))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.view_widget = QtWidgets.QWidget(self.centralwidget)
        self.view_widget.setMinimumSize(QtCore.QSize(530, 530))
        self.view_widget.setObjectName("view_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.view_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.img_view = QtWidgets.QLabel(self.view_widget)
        self.img_view.setMinimumSize(QtCore.QSize(512, 512))
        self.img_view.setFrameShape(QtWidgets.QFrame.Panel)
        self.img_view.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.img_view.setText("")
        self.img_view.setAlignment(QtCore.Qt.AlignCenter)
        self.img_view.setObjectName("img_view")
        self.verticalLayout.addWidget(self.img_view)
        self.gridLayout.addWidget(self.view_widget, 0, 0, 1, 1)
        self.edit_widget = QtWidgets.QWidget(self.centralwidget)
        self.edit_widget.setMinimumSize(QtCore.QSize(102, 530))
        self.edit_widget.setMaximumSize(QtCore.QSize(102, 16777215))
        self.edit_widget.setObjectName("edit_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.edit_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.light_label = QtWidgets.QLabel(self.edit_widget)
        self.light_label.setAutoFillBackground(False)
        self.light_label.setTextFormat(QtCore.Qt.AutoText)
        self.light_label.setObjectName("light_label")
        self.verticalLayout_2.addWidget(self.light_label)
        self.light_spinbox = QtWidgets.QSpinBox(self.edit_widget)
        self.light_spinbox.setEnabled(False)
        self.light_spinbox.setAlignment(QtCore.Qt.AlignCenter)
        self.light_spinbox.setMinimum(-255)
        self.light_spinbox.setMaximum(255)
        self.light_spinbox.setSingleStep(5)
        self.light_spinbox.setObjectName("light_spinbox")
        self.verticalLayout_2.addWidget(self.light_spinbox)
        self.contrast_label = QtWidgets.QLabel(self.edit_widget)
        self.contrast_label.setObjectName("contrast_label")
        self.verticalLayout_2.addWidget(self.contrast_label)
        self.contrast_spinbox = QtWidgets.QDoubleSpinBox(self.edit_widget)
        self.contrast_spinbox.setEnabled(False)
        self.contrast_spinbox.setAlignment(QtCore.Qt.AlignCenter)
        self.contrast_spinbox.setDecimals(2)
        self.contrast_spinbox.setMinimum(-10.0)
        self.contrast_spinbox.setMaximum(10.0)
        self.contrast_spinbox.setSingleStep(0.1)
        self.contrast_spinbox.setProperty("value", 1.0)
        self.contrast_spinbox.setObjectName("contrast_spinbox")
        self.verticalLayout_2.addWidget(self.contrast_spinbox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout.addWidget(self.edit_widget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 656, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuFilters = QtWidgets.QMenu(self.menuEdit)
        self.menuFilters.setEnabled(False)
        self.menuFilters.setObjectName("menuFilters")
        self.menuTransformations = QtWidgets.QMenu(self.menuEdit)
        self.menuTransformations.setEnabled(False)
        self.menuTransformations.setObjectName("menuTransformations")
        self.menuRotate = QtWidgets.QMenu(self.menuTransformations)
        self.menuRotate.setObjectName("menuRotate")
        self.menuColor = QtWidgets.QMenu(self.menuTransformations)
        self.menuColor.setObjectName("menuColor")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setEnabled(False)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setEnabled(False)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionCustom = QtWidgets.QAction(MainWindow)
        self.actionCustom.setObjectName("actionCustom")
        self.actionLaplace = QtWidgets.QAction(MainWindow)
        self.actionLaplace.setObjectName("actionLaplace")
        self.actionGaussian = QtWidgets.QAction(MainWindow)
        self.actionGaussian.setObjectName("actionGaussian")
        self.actionSobel = QtWidgets.QAction(MainWindow)
        self.actionSobel.setObjectName("actionSobel")
        self.action90_degree = QtWidgets.QAction(MainWindow)
        self.action90_degree.setObjectName("action90_degree")
        self.action180_degree = QtWidgets.QAction(MainWindow)
        self.action180_degree.setObjectName("action180_degree")
        self.action270_degree = QtWidgets.QAction(MainWindow)
        self.action270_degree.setObjectName("action270_degree")
        self.actionSet_degree = QtWidgets.QAction(MainWindow)
        self.actionSet_degree.setObjectName("actionSet_degree")
        self.actionLight_Contrast = QtWidgets.QAction(MainWindow)
        self.actionLight_Contrast.setObjectName("actionLight_Contrast")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionExit)
        self.menuFilters.addAction(self.actionCustom)
        self.menuFilters.addSeparator()
        self.menuFilters.addAction(self.actionLaplace)
        self.menuFilters.addAction(self.actionGaussian)
        self.menuFilters.addAction(self.actionSobel)
        self.menuRotate.addAction(self.action90_degree)
        self.menuRotate.addAction(self.action180_degree)
        self.menuRotate.addAction(self.action270_degree)
        self.menuRotate.addSeparator()
        self.menuRotate.addAction(self.actionSet_degree)
        self.menuColor.addAction(self.actionLight_Contrast)
        self.menuTransformations.addAction(self.menuRotate.menuAction())
        self.menuTransformations.addAction(self.menuColor.menuAction())
        self.menuEdit.addAction(self.menuFilters.menuAction())
        self.menuEdit.addAction(self.menuTransformations.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Test Window "))
        self.light_label.setText(_translate("MainWindow", "Light:"))
        self.contrast_label.setText(_translate("MainWindow", "Contrast:"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuFilters.setTitle(_translate("MainWindow", "Filters"))
        self.menuTransformations.setTitle(_translate("MainWindow", "Transformations"))
        self.menuRotate.setTitle(_translate("MainWindow", "Rotate"))
        self.menuColor.setTitle(_translate("MainWindow", "Color"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setStatusTip(_translate("MainWindow", "Opening an image"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setStatusTip(_translate("MainWindow", "Saving an image"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setStatusTip(_translate("MainWindow", "Application Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))
        self.actionSave_as.setStatusTip(_translate("MainWindow", "Saving an image as ..."))
        self.actionSave_as.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionCustom.setText(_translate("MainWindow", "Custom"))
        self.actionLaplace.setText(_translate("MainWindow", "Laplace"))
        self.actionGaussian.setText(_translate("MainWindow", "Gaussian"))
        self.actionSobel.setText(_translate("MainWindow", "Sobel"))
        self.action90_degree.setText(_translate("MainWindow", "90 degree"))
        self.action180_degree.setText(_translate("MainWindow", "180 degree"))
        self.action270_degree.setText(_translate("MainWindow", "270 degree"))
        self.actionSet_degree.setText(_translate("MainWindow", "Set degree"))
        self.actionLight_Contrast.setText(_translate("MainWindow", "Light/Contrast"))

