# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'color_processing.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogColoring(object):
    def setupUi(self, DialogColoring):
        DialogColoring.setObjectName("DialogColoring")
        DialogColoring.resize(400, 420)
        DialogColoring.setMinimumSize(QtCore.QSize(400, 420))
        DialogColoring.setMaximumSize(QtCore.QSize(400, 420))
        self.gridLayout = QtWidgets.QGridLayout(DialogColoring)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(DialogColoring)
        self.tabWidget.setMinimumSize(QtCore.QSize(380, 340))
        self.tabWidget.setMaximumSize(QtCore.QSize(380, 340))
        self.tabWidget.setObjectName("tabWidget")
        self.light_process = QtWidgets.QWidget()
        self.light_process.setAccessibleName("")
        self.light_process.setObjectName("light_process")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.light_process)
        self.verticalLayout.setObjectName("verticalLayout")
        self.l_radio = QtWidgets.QWidget(self.light_process)
        self.l_radio.setMaximumSize(QtCore.QSize(16777215, 40))
        self.l_radio.setObjectName("l_radio")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.l_radio)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.l_radio_all_bands = QtWidgets.QRadioButton(self.l_radio)
        self.l_radio_all_bands.setChecked(True)
        self.l_radio_all_bands.setObjectName("l_radio_all_bands")
        self.horizontalLayout_2.addWidget(self.l_radio_all_bands)
        self.l_radio_rgb = QtWidgets.QRadioButton(self.l_radio)
        self.l_radio_rgb.setObjectName("l_radio_rgb")
        self.horizontalLayout_2.addWidget(self.l_radio_rgb)
        self.verticalLayout.addWidget(self.l_radio)
        self.l_widgets_options = QtWidgets.QWidget(self.light_process)
        self.l_widgets_options.setObjectName("l_widgets_options")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.l_widgets_options)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.l_all_bands_widget = QtWidgets.QWidget(self.l_widgets_options)
        self.l_all_bands_widget.setObjectName("l_all_bands_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.l_all_bands_widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.l_light_for_all = QtWidgets.QLabel(self.l_all_bands_widget)
        self.l_light_for_all.setObjectName("l_light_for_all")
        self.verticalLayout_4.addWidget(self.l_light_for_all)
        self.l_spin_light_for_all = QtWidgets.QSpinBox(self.l_all_bands_widget)
        self.l_spin_light_for_all.setMinimum(-255)
        self.l_spin_light_for_all.setMaximum(255)
        self.l_spin_light_for_all.setSingleStep(5)
        self.l_spin_light_for_all.setObjectName("l_spin_light_for_all")
        self.verticalLayout_4.addWidget(self.l_spin_light_for_all)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_3.addWidget(self.l_all_bands_widget)
        self.l_rgb_widget = QtWidgets.QWidget(self.l_widgets_options)
        self.l_rgb_widget.setEnabled(False)
        self.l_rgb_widget.setObjectName("l_rgb_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.l_rgb_widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.l_red = QtWidgets.QLabel(self.l_rgb_widget)
        self.l_red.setObjectName("l_red")
        self.verticalLayout_3.addWidget(self.l_red)
        self.l_spin_red = QtWidgets.QSpinBox(self.l_rgb_widget)
        self.l_spin_red.setMinimum(-255)
        self.l_spin_red.setMaximum(255)
        self.l_spin_red.setSingleStep(5)
        self.l_spin_red.setObjectName("l_spin_red")
        self.verticalLayout_3.addWidget(self.l_spin_red)
        self.l_green = QtWidgets.QLabel(self.l_rgb_widget)
        self.l_green.setObjectName("l_green")
        self.verticalLayout_3.addWidget(self.l_green)
        self.l_spin_green = QtWidgets.QSpinBox(self.l_rgb_widget)
        self.l_spin_green.setMinimum(-255)
        self.l_spin_green.setMaximum(255)
        self.l_spin_green.setSingleStep(5)
        self.l_spin_green.setObjectName("l_spin_green")
        self.verticalLayout_3.addWidget(self.l_spin_green)
        self.l_blue = QtWidgets.QLabel(self.l_rgb_widget)
        self.l_blue.setObjectName("l_blue")
        self.verticalLayout_3.addWidget(self.l_blue)
        self.l_spin_blue = QtWidgets.QSpinBox(self.l_rgb_widget)
        self.l_spin_blue.setMinimum(-255)
        self.l_spin_blue.setMaximum(255)
        self.l_spin_blue.setSingleStep(5)
        self.l_spin_blue.setObjectName("l_spin_blue")
        self.verticalLayout_3.addWidget(self.l_spin_blue)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_3.addWidget(self.l_rgb_widget)
        self.verticalLayout.addWidget(self.l_widgets_options)
        self.tabWidget.addTab(self.light_process, "")
        self.contrast_process = QtWidgets.QWidget()
        self.contrast_process.setObjectName("contrast_process")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.contrast_process)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.c_radio = QtWidgets.QWidget(self.contrast_process)
        self.c_radio.setMinimumSize(QtCore.QSize(0, 40))
        self.c_radio.setMaximumSize(QtCore.QSize(16777215, 40))
        self.c_radio.setObjectName("c_radio")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.c_radio)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.c_radio_all_bands = QtWidgets.QRadioButton(self.c_radio)
        self.c_radio_all_bands.setChecked(True)
        self.c_radio_all_bands.setObjectName("c_radio_all_bands")
        self.horizontalLayout_4.addWidget(self.c_radio_all_bands)
        self.c_radio_rgb = QtWidgets.QRadioButton(self.c_radio)
        self.c_radio_rgb.setObjectName("c_radio_rgb")
        self.horizontalLayout_4.addWidget(self.c_radio_rgb)
        self.verticalLayout_2.addWidget(self.c_radio)
        self.c_widgets_options = QtWidgets.QWidget(self.contrast_process)
        self.c_widgets_options.setObjectName("c_widgets_options")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.c_widgets_options)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.c_all_bands_widget = QtWidgets.QWidget(self.c_widgets_options)
        self.c_all_bands_widget.setObjectName("c_all_bands_widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.c_all_bands_widget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.c_double_spin_for_all = QtWidgets.QLabel(self.c_all_bands_widget)
        self.c_double_spin_for_all.setObjectName("c_double_spin_for_all")
        self.verticalLayout_5.addWidget(self.c_double_spin_for_all)
        self.c_contrast_for_all = QtWidgets.QDoubleSpinBox(self.c_all_bands_widget)
        self.c_contrast_for_all.setMinimum(-10.0)
        self.c_contrast_for_all.setMaximum(10.0)
        self.c_contrast_for_all.setSingleStep(0.1)
        self.c_contrast_for_all.setProperty("value", 1.0)
        self.c_contrast_for_all.setObjectName("c_contrast_for_all")
        self.verticalLayout_5.addWidget(self.c_contrast_for_all)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.horizontalLayout_5.addWidget(self.c_all_bands_widget)
        self.c_rgb_widget = QtWidgets.QWidget(self.c_widgets_options)
        self.c_rgb_widget.setEnabled(False)
        self.c_rgb_widget.setObjectName("c_rgb_widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.c_rgb_widget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.c_red = QtWidgets.QLabel(self.c_rgb_widget)
        self.c_red.setObjectName("c_red")
        self.verticalLayout_6.addWidget(self.c_red)
        self.c_double_spin_red = QtWidgets.QDoubleSpinBox(self.c_rgb_widget)
        self.c_double_spin_red.setMinimum(-10.0)
        self.c_double_spin_red.setMaximum(10.0)
        self.c_double_spin_red.setSingleStep(0.1)
        self.c_double_spin_red.setProperty("value", 1.0)
        self.c_double_spin_red.setObjectName("c_double_spin_red")
        self.verticalLayout_6.addWidget(self.c_double_spin_red)
        self.c_green = QtWidgets.QLabel(self.c_rgb_widget)
        self.c_green.setObjectName("c_green")
        self.verticalLayout_6.addWidget(self.c_green)
        self.c_double_spin_green = QtWidgets.QDoubleSpinBox(self.c_rgb_widget)
        self.c_double_spin_green.setMinimum(-10.0)
        self.c_double_spin_green.setMaximum(10.0)
        self.c_double_spin_green.setSingleStep(0.1)
        self.c_double_spin_green.setProperty("value", 1.0)
        self.c_double_spin_green.setObjectName("c_double_spin_green")
        self.verticalLayout_6.addWidget(self.c_double_spin_green)
        self.c_blue = QtWidgets.QLabel(self.c_rgb_widget)
        self.c_blue.setObjectName("c_blue")
        self.verticalLayout_6.addWidget(self.c_blue)
        self.c_double_spin_blue = QtWidgets.QDoubleSpinBox(self.c_rgb_widget)
        self.c_double_spin_blue.setMinimum(-10.0)
        self.c_double_spin_blue.setMaximum(10.0)
        self.c_double_spin_blue.setSingleStep(0.1)
        self.c_double_spin_blue.setProperty("value", 1.0)
        self.c_double_spin_blue.setObjectName("c_double_spin_blue")
        self.verticalLayout_6.addWidget(self.c_double_spin_blue)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.horizontalLayout_5.addWidget(self.c_rgb_widget)
        self.verticalLayout_2.addWidget(self.c_widgets_options)
        self.tabWidget.addTab(self.contrast_process, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(DialogColoring)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.cancel_button = QtWidgets.QPushButton(self.widget)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.compute_button = QtWidgets.QPushButton(self.widget)
        self.compute_button.setObjectName("compute_button")
        self.horizontalLayout.addWidget(self.compute_button)
        self.gridLayout.addWidget(self.widget, 1, 0, 1, 1)

        self.retranslateUi(DialogColoring)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DialogColoring)
        DialogColoring.setTabOrder(self.tabWidget, self.l_radio_all_bands)
        DialogColoring.setTabOrder(self.l_radio_all_bands, self.l_radio_rgb)
        DialogColoring.setTabOrder(self.l_radio_rgb, self.l_spin_light_for_all)
        DialogColoring.setTabOrder(self.l_spin_light_for_all, self.l_spin_red)
        DialogColoring.setTabOrder(self.l_spin_red, self.l_spin_green)
        DialogColoring.setTabOrder(self.l_spin_green, self.l_spin_blue)
        DialogColoring.setTabOrder(self.l_spin_blue, self.cancel_button)
        DialogColoring.setTabOrder(self.cancel_button, self.compute_button)
        DialogColoring.setTabOrder(self.compute_button, self.c_radio_all_bands)
        DialogColoring.setTabOrder(self.c_radio_all_bands, self.c_radio_rgb)
        DialogColoring.setTabOrder(self.c_radio_rgb, self.c_contrast_for_all)
        DialogColoring.setTabOrder(self.c_contrast_for_all, self.c_double_spin_red)
        DialogColoring.setTabOrder(self.c_double_spin_red, self.c_double_spin_green)
        DialogColoring.setTabOrder(self.c_double_spin_green, self.c_double_spin_blue)

    def retranslateUi(self, DialogColoring):
        _translate = QtCore.QCoreApplication.translate
        DialogColoring.setWindowTitle(_translate("DialogColoring", "Color Editing"))
        self.l_radio_all_bands.setText(_translate("DialogColoring", "All Bands"))
        self.l_radio_rgb.setText(_translate("DialogColoring", "RGB"))
        self.l_light_for_all.setText(_translate("DialogColoring", "Light for all:"))
        self.l_red.setText(_translate("DialogColoring", "Red:"))
        self.l_green.setText(_translate("DialogColoring", "Green:"))
        self.l_blue.setText(_translate("DialogColoring", "Blue:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.light_process), _translate("DialogColoring", "Light"))
        self.c_radio_all_bands.setText(_translate("DialogColoring", "All Bands"))
        self.c_radio_rgb.setText(_translate("DialogColoring", "RGB"))
        self.c_double_spin_for_all.setText(_translate("DialogColoring", "Contrast for all:"))
        self.c_red.setText(_translate("DialogColoring", "Red:"))
        self.c_green.setText(_translate("DialogColoring", "Green:"))
        self.c_blue.setText(_translate("DialogColoring", "Blue:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.contrast_process), _translate("DialogColoring", "Contrast"))
        self.cancel_button.setText(_translate("DialogColoring", "Cancel"))
        self.compute_button.setText(_translate("DialogColoring", "Compute"))

